name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

      - name: Generate Allure report
        run: mvn allure:report

      - name: Install Allure commandline
        run: |
          curl -o allure.zip -L "https://dl.bintray.com/qameta/generic/allure/2.17.2/allure-commandline-2.17.2.zip"
          unzip allure.zip -d allure
          sudo mv allure/bin/* /usr/local/bin/

      - name: Archive Allure report
        run: |
          mkdir allure-report
          cp -R target/allure-results allure-report/
          cp -R target/site/allure-maven/ allure-report/

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report/
